export const LOAD_TOP_OFFERS_START = 'LOAD_TOP_OFFERS_START';
export const LOAD_TOP_OFFERS_SUCCESS = 'LOAD_TOP_OFFERS_SUCCESS';
export const LOAD_TOP_OFFERS_FAILURE = 'LOAD_TOP_OFFERS_FAILURE';

export const OFFER_SEARCH_START = 'OFFER_SEARCH_START';
export const OFFER_SEARCH_SUCCESS = 'OFFER_SEARCH_SUCCESS';
export const OFFER_SEARCH_FAILURE = 'OFFER_SEARCH_FAILURE';

export const OFFER_SELECT_SORT = 'OFFER_SELECT_SORT';
export const OFFER_SELECT_PAGE = 'OFFER_SELECT_PAGE';

export const LOAD_OFFER_FOR_EDIT = 'LOAD_OFFER_FOR_EDIT';
export const RESET_OFFER_OBJECT = 'RESET_OFFER_OBJECT';
