export const LOAD_TOP_OFFERS_START = 'LOAD_TOP_OFFERS_START';
export const LOAD_TOP_OFFERS_SUCCESS = 'LOAD_TOP_OFFERS_SUCCESS';
export const LOAD_TOP_OFFERS_FAILURE = 'LOAD_TOP_OFFERS_FAILURE';

export const OFFER_SEARCH_START = 'OFFER_SEARCH_START';
export const OFFER_SEARCH_SUCCESS = 'OFFER_SEARCH_SUCCESS';
export const OFFER_SEARCH_FAILURE = 'OFFER_SEARCH_FAILURE';
