export const FETCH_MAKERS_START = 'FETCH_MAKERS_START';
export const FETCH_MAKERS_SUCCESS = 'FETCH_MAKERS_SUCCESS';
export const FETCH_MAKERS_FAILURE = 'FETCH_MAKERS_FAILURE';

export const FETCH_STATISTICS_START = 'FETCH_STATISTICS_START';
export const FETCH_STATISTICS_SUCCESS = 'FETCH_STATISTICS_SUCCESS';
export const FETCH_STATISTICS_FAILURE = 'FETCH_STATISTICS_FAILURE';

export const FETCH_APP_STATE_START = 'FETCH_APP_STATE_START';
export const FETCH_APP_STATE_SUCCESS = 'FETCH_APP_STATE_SUCCESS';
export const FETCH_METADATA_SUCCESS = 'FETCH_METADATA_SUCCESS';
export const FETCH_APP_STATE_FAILURE = 'FETCH_APP_STATE_FAILURE';
