export const FETCH_MAKERS_START = 'FETCH_MAKERS_START';
export const FETCH_MAKERS_SUCCESS = 'FETCH_MAKERS_SUCCESS';
export const FETCH_MAKERS_FAILURE = 'FETCH_MAKERS_FAILURE';
export const FETCH_STATISTICS_SUCCESS = 'FETCH_STATISTICS_SUCCESS';
